#!/usr/bin/env lua

local what = select(3, ...)
local json = require 'json'
local file = io.open('data/help.json')
local data = json.decode(file:read())
local desc = data[what]

if desc then
    print(what .. ": " .. desc)
elseif not what then
    local commands = {}
    for k,_ in pairs(data) do table.insert(commands, k) end

    print("Commands: " .. table.concat(commands, ", "))
else
    print("That command doesn't have a help entry")
end
