#!/usr/bin/env lua

local msg, from, level = ...
local json             = require 'json'

local function setIgnore(user, val)
    local file = io.open('data/ignore.json')
    local data = json.decode(file:read())
    file:close()
    file = io.open('data/ignore.json', 'w')

    data[user]  = val
    file:write(json.encode(data))
    file:close()
end

if tonumber(level) == 1 then
    setIgnore(msg, true)
    print(from .. ": " .. msg .. " has been ignored.")
else
    print(from .. ": Insufficient permissions")
end
