#!/usr/bin/env lua

-- modules
local http = require 'socket.http'
local url  = require 'socket.url'
local json = require 'json'

-- get data
local result
local msg, from, level = ...
local suc = pcall(function()
    result = http.request("http://www.xkcd.com/" .. (msg and msg .. '/' or '') ..'info.0.json')
    result = json.decode(result)
    result = result.title .. "-> " .. result.img
end)

if suc then
    print(from .. ": " .. result)
else
    print(from .. ": Invalid comic")
end
